print("======Basic file Handling======")
file = open('introduction.txt', 'w')
file.write('name: Adithyan\n')
file.write('age: 21\n')
file.write('branch: BCA\n')
file.write('college: University of Calicut\n')
file.write('domain: data analytics\n')
file.close()
print("File created successfully!")
file = open('introduction.txt', 'r')
content = file.read()
print('\n=====File Content=====')
print(content)
file.close()